sudo: required
services:
  - docker

before_install:
  - docker build -t cihanulas/my-react -f Dockerfile.dev .
script:
  - docker run -e CI=true cihanulas/my-react npm run test
deploy: # require aws account.
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "myreact"
  env: "Docker-env"
  bucket_name: "elastic-beanstalk-us-west-2...."
  bucket_path: "myreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY # create as env in travis.
  secret_access_key:
    secure: $AWS_SECRET_KEY
