
# get a base image for node.js
FROM node:alpine

RUN npm install

# tell the işmage what do do when it starts as containter.
CMD ["npm", "start"]

# docker build . 
# we get the warning when we build. 
# npm WARN saveError ENOENT: no such file or