
# get a base image for node.js
FROM node:alpine

RUN npm install

# tell the işmage what do do when it starts as containter.
CMD ["npm", "start"]

# docker build . 
# Successfully built 2b8a097d4c40
# docker run -it 2b8a097d4c400+


